language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then apt-get update && apt-get update sfml; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sfml; fi
script:
- make
after_success:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build_support.sh archive_codedb; fi
branches:
  only:
  - master
  - "/^v\\d+\\./"
